#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xlProtocol_go
  
  rm -rf chunks/tmp/* 
  
  pySloc -L go   -X *.pb.go -v $@
else
  echo "DEV_BASE is not defined"
fi
